# ═══════════════════════════════════════════════════════════════════════════════
# SDDA - Analysis Options
# Configuración estricta para código de alta calidad
# ═══════════════════════════════════════════════════════════════════════════════

include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "**/*.config.dart"
    - "build/**"
    - ".dart_tool/**"

  errors:
    # Errores que DEBEN corregirse
    invalid_annotation_target: error
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
    unnecessary_type_check: error

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    # ═══════════════════════════════════════════════════════════════════════════
    # REGLAS DE ESTILO
    # ═══════════════════════════════════════════════════════════════════════════

    # Preferir comillas simples
    prefer_single_quotes: true

    # Líneas de hasta 120 caracteres (más práctico que 80)
    lines_longer_than_80_chars: false

    # Documentación pública opcional (se documenta lo necesario)
    public_member_api_docs: false

    # Ordenar imports alfabéticamente
    directives_ordering: true
    sort_pub_dependencies: true

    # ═══════════════════════════════════════════════════════════════════════════
    # REGLAS DE CÓDIGO
    # ═══════════════════════════════════════════════════════════════════════════

    # Evitar código muerto
    avoid_unused_constructor_parameters: true
    avoid_returning_null_for_void: true

    # Preferencias de sintaxis moderna
    prefer_final_locals: true
    prefer_final_in_for_each: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true

    # Nulos y opcionales
    avoid_null_checks_in_equality_operators: true
    prefer_null_aware_method_calls: true
    prefer_null_aware_operators: true

    # Colecciones
    prefer_collection_literals: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_iterable_whereType: true

    # Funciones
    prefer_expression_function_bodies: false  # A veces es más legible el bloque
    unnecessary_lambdas: true
    avoid_returning_this: true

    # Clases
    sort_constructors_first: true
    prefer_constructors_over_static_methods: true
    use_setters_to_change_properties: true

    # Async
    await_only_futures: true
    avoid_void_async: true
    unawaited_futures: true

    # Flutter específico
    use_build_context_synchronously: true
    use_key_in_widget_constructors: true
    sized_box_for_whitespace: true
    sized_box_shrink_expand: true

    # ═══════════════════════════════════════════════════════════════════════════
    # REGLAS DE SEGURIDAD
    # ═══════════════════════════════════════════════════════════════════════════

    # Evitar print en producción
    avoid_print: true

    # Type safety
    avoid_dynamic_calls: true
    avoid_types_on_closure_parameters: false
    omit_local_variable_types: false  # Preferimos tipos explícitos para claridad

    # ═══════════════════════════════════════════════════════════════════════════
    # REGLAS DE TESTING
    # ═══════════════════════════════════════════════════════════════════════════

    # Tests bien estructurados
    test_types_in_equals: true
